"""Pydantic models for request/response schemas."""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class VideoStyle(str, Enum):
    """Video style options."""

    educational = "educational"
    entertaining = "entertaining"
    documentary = "documentary"
    motivational = "motivational"
    news = "news"


class VideoFormat(str, Enum):
    """Video format/orientation options."""

    shorts = "shorts"  # 1080x1920 vertical
    landscape = "landscape"  # 1920x1080 horizontal


class Resolution(str, Enum):
    """Video resolution presets."""

    res_480p = "480p"
    res_720p = "720p"
    res_1080p = "1080p"
    res_4k = "4k"


class BitratePreset(str, Enum):
    """Video bitrate presets."""

    low = "low"
    medium = "medium"
    high = "high"
    custom = "custom"


class FPSOption(str, Enum):
    """Frames per second options."""

    fps_24 = "24"
    fps_30 = "30"
    fps_60 = "60"


class CodecPreset(str, Enum):
    """FFmpeg codec speed presets."""

    ultrafast = "ultrafast"
    superfast = "superfast"
    veryfast = "veryfast"
    faster = "faster"
    fast = "fast"
    medium = "medium"
    slow = "slow"
    slower = "slower"
    veryslow = "veryslow"


class OutputFormat(str, Enum):
    """Video output file format."""

    mp4 = "mp4"
    webm = "webm"
    avi = "avi"


class VideoQualitySettings(BaseModel):
    """Video quality configuration settings."""

    resolution: Resolution = Field(
        default=Resolution.res_1080p, description="Video resolution"
    )
    bitrate: BitratePreset = Field(
        default=BitratePreset.medium, description="Bitrate preset"
    )
    custom_bitrate: Optional[str] = Field(
        None, description="Custom bitrate value (e.g. '6M'), used when bitrate is 'custom'"
    )
    fps: FPSOption = Field(default=FPSOption.fps_24, description="Frames per second")
    codec_preset: CodecPreset = Field(
        default=CodecPreset.medium, description="FFmpeg codec speed preset"
    )
    output_format: OutputFormat = Field(
        default=OutputFormat.mp4, description="Output file format"
    )


class AudioSettings(BaseModel):
    """Audio processing configuration settings."""

    crossfade_duration: float = Field(
        default=0.5, ge=0.0, le=2.0, description="Crossfade duration between scenes in seconds"
    )
    normalize_audio: bool = Field(
        default=True, description="Normalize audio volume across all scenes"
    )
    background_music_url: Optional[str] = Field(
        default=None, description="URL of background music file to mix in"
    )
    background_music_volume: float = Field(
        default=0.15, ge=0.0, le=1.0, description="Background music volume (0.0 to 1.0)"
    )
    enable_ducking: bool = Field(
        default=True, description="Auto-duck background music during narration"
    )
    generate_subtitles: bool = Field(
        default=False, description="Generate SRT subtitle file alongside the video"
    )


class VideoRequest(BaseModel):
    """Request model for video generation."""

    topic: str = Field(..., min_length=3, max_length=500, description="Video topic")
    duration_minutes: float = Field(
        default=1.0, ge=0.5, le=10.0, description="Desired video duration in minutes"
    )
    style: VideoStyle = Field(
        default=VideoStyle.educational, description="Video style"
    )
    format: VideoFormat = Field(
        default=VideoFormat.landscape, description="Video format/orientation"
    )


class ScriptScene(BaseModel):
    """A single scene in the video script."""

    scene_number: int = Field(..., description="Scene sequence number")
    narration: str = Field(..., description="Narration text for this scene")
    visual_description: str = Field(
        ..., description="Description of visuals for this scene"
    )
    duration_seconds: float = Field(
        ..., ge=2.0, le=60.0, description="Scene duration in seconds"
    )


class VideoScript(BaseModel):
    """Complete video script generated by AI."""

    title: str = Field(..., description="Video title")
    scenes: list[ScriptScene] = Field(..., min_length=1, description="List of scenes")
    total_duration: float = Field(..., description="Total duration in seconds")


class MediaType(str, Enum):
    """Types of media that can be sourced."""

    video = "video"
    image = "image"
    gif = "gif"


class MediaItem(BaseModel):
    """A media item sourced for a scene."""

    url: str = Field(..., description="URL of the media")
    local_path: Optional[str] = Field(None, description="Local file path after download")
    media_type: MediaType = Field(..., description="Type of media")
    source: str = Field(..., description="Source API (pexels, pixabay, giphy)")
    query: str = Field(..., description="Search query used")
    width: Optional[int] = None
    height: Optional[int] = None


class SceneMedia(BaseModel):
    """Media items for a specific scene."""

    scene_number: int
    media_items: list[MediaItem] = Field(default_factory=list)


class TTSResult(BaseModel):
    """Result of TTS generation for a scene."""

    scene_number: int = Field(..., description="Scene number")
    audio_path: str = Field(..., description="Path to generated audio file")
    duration_seconds: float = Field(..., description="Audio duration in seconds")


class VideoResult(BaseModel):
    """Result of video assembly."""

    video_id: str = Field(..., description="Unique video identifier")
    video_path: str = Field(..., description="Path to the assembled video")
    duration_seconds: float = Field(..., description="Total video duration")
    scenes_count: int = Field(..., description="Number of scenes")
    format: VideoFormat = Field(..., description="Video format")
    subtitle_path: Optional[str] = Field(
        default=None, description="Path to generated SRT subtitle file"
    )


class GenerateScriptRequest(BaseModel):
    """Request to generate a video script."""

    topic: str = Field(..., min_length=3, max_length=500)
    duration_minutes: float = Field(default=1.0, ge=0.5, le=10.0)
    style: VideoStyle = Field(default=VideoStyle.educational)


class GenerateTTSRequest(BaseModel):
    """Request to generate TTS audio from a script."""

    script: VideoScript
    voice: Optional[str] = None


class SourceMediaRequest(BaseModel):
    """Request to source media for a script."""

    script: VideoScript
    preferred_type: Optional[MediaType] = None


class AssembleVideoRequest(BaseModel):
    """Request to assemble the final video."""

    script: VideoScript
    tts_results: list[TTSResult]
    scene_media: list[SceneMedia]
    format: VideoFormat = Field(default=VideoFormat.landscape)
    quality_settings: Optional[VideoQualitySettings] = Field(
        default=None, description="Optional video quality settings"
    )
    audio_settings: Optional[AudioSettings] = Field(
        default=None, description="Optional audio processing settings"
    )


class GenerateFullRequest(BaseModel):
    """Request for the full pipeline generation via SSE."""

    topic: str = Field(..., min_length=3, max_length=500)
    duration_minutes: float = Field(default=1.0, ge=0.5, le=10.0)
    style: VideoStyle = Field(default=VideoStyle.educational)
    quality_settings: Optional[VideoQualitySettings] = Field(
        default=None, description="Optional video quality settings"
    )
    audio_settings: Optional[AudioSettings] = Field(
        default=None, description="Optional audio processing settings"
    )
